### PR TITLE
Fixes for memory leak in pix images, unnecessary reinitialization, and api additions

### LINKED ISSUE #124: Tesseract BaseAPI memory leak
Continued from #123...

There seems to be a memory leak issue in the Tesseract BaseAPI.End() function. When calling the End() function and letting client go out of scope, memory usage decreases slightly, but still takes up a couple megabytes of memory for each client struct created.

This can be seen by running the below test program:

```go
package main

import (
	"fmt"
	"github.com/otiai10/gosseract"
	"time"
)

func main() {

	var count int

	var clients []*gosseract.Client

	for _ = range time.Tick(time.Millisecond * 100) {
		client := gosseract.NewClient()

		client.SetImage("002-confusing.png")
		text, _ := client.Text()
		_, _ = client.HOCRText()
		fmt.Println(text)
		// Hello, World!
		count++

		clients = append(clients, client)

		if count == 20 {
			break
		}
	}

	for _ = range time.Tick(time.Millisecond * 10) {
		count--
		if count == 0 {
			break
		}
	}

	for _, c := range clients {
		(*c).Close()
	}

	for _ = range time.Tick(time.Second * 1) {
	}
}
```

For some reason, after the clients are closed and the tesseract BaseAPI End() method should be called, memory usage will remain elevated. I have tried calling the Go garbage collector functions and it seems to make no difference. The only way I have found to release the memory is to exit the program.

I looked through the gosseract library .cpp file and have not seen any bugs, so this may be a tesseract library issue.

Tesseract BaseAPI End method reference: https://zdenop.github.io/tesseract-doc/group___advanced_a_p_i.html#ga38027513ee9c0348de1790bddcdc3391

### PR DESCRIPTION
**Pull request by will7200**
This should fix #124 in regards to deleting pix images created.
Additions in the Tesseract API include:
tesseract::TessBaseAPI::ClearPersistentCache
tesseract::TessBaseAPI::Clear

Alias for pixDestory -- DestoryPixImage

I also added some checks so that the client is not always reinitializing a client that has already been initialized, it causes performance degradation as seen in the benchmark if reused. The client will also no longer call the c API to set the image on every text or HOCRText call if a pix image has already been set and was not called previously.

Benchmark reusing a client:
oos: darwin
goarch: amd64
pkg: github.com/otiai10/gosseract
BenchmarkClient_Text-4                 5         213477008 ns/op
BenchmarkClient_Text2-4               30          39615045 ns/op
PASS
ok      github.com/otiai10/gosseract    4.680s

### CODE REVIEW

**Comment by otiai10** [comment]
@will7200 Thank you very much!

File: client.go [hunk 1]
```diff
@@ -79,24 +93,34 @@ func (client *Client) Close() (err error) {
...
 
 // SetImage sets path to image file to be processed OCR.
 func (client *Client) SetImage(imagepath string) *Client {
+	if client.pixImage != nil {
+		C.DestroyPixImage(client.pixImage)
+		client.pixImage = nil
+	}
 	client.ImagePath = imagepath
 	return client
 }
```
Comment (otiai10) [inline client.go]: seems I should change the interface of some methods to return errors explicitly, such like

```go
func (client *Client) SetImage(imagepath string) error
```

@otiai10 I will do it after it gets merged

**Comment by otiai10** [comment]
The pull request seems quite cool. Thank you again.

I want to ask you a comment for one point.

----

I guess `ImagePath` property is no longer needed, with initializing `pixImage` with each call of `SetImage` or `SetImageFromBytes` like this

```go
if client.pixImage != nil {
    C.DestroyPixImage(client.pixImage)
    client.pixImage = nil
}
imagepath := C.CString(client.ImagePath)
defer C.free(unsafe.Pointer(imagepath))
img := C.SetImage(client.api, imagepath)
client.pixImage = img
return nil
```

- *Pros*
    - Code would be simple and plain.
        - `prepare`, particularly
- *Cons*
    - The cost of each call of `SetImage` or `SetImageFromBytes` raises.
        - not good for usecase in which `SetImage` is called many times for 1 client.

What do you think? @will7200

**Comment by will7200** [comment]
I forgot to check if the pixImage was closed on client close. Added.

File: client.go (hunk 1 above)
Comment (will7200) [reply client.go]: I think that would be beneficial since we are using Leptonica on the c side and not checking any errors c side. SetImage should check that the imagepath is not blank and that it is a valid path on the os. I added these to prepare function.

**Comment by will7200** [comment]
Well, I was thinking that prepare, for the most part, is not necessary.
Considering that you have Setters for variables, pageSegMode, config, and languages, prepare should be refactored out. For example, if a client is reusing an image that means it has to set all the variables again as well as the Paging mode. Sure the cost of each set call raises, but it is not doing any meaningless calls either. The only real benefit of having prepare is that is sets the pixImage again
if repeated Text calls are made, I am not sure why but the ExampleClient_SetWhitelist fails to complete unless the image is set again after calling text.

I cannot see a use case for repeatedly calling setimage or setimagefrombytes multiple times before calling Text or HOCRText. Ideally, if someone is making a call to SetImage or ther other, it is because they are setting a new image.
